# frozen_string_literal: true

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'bat'
brew 'exa'
# brew 'exercism'
brew 'fd'
brew 'fzf'
# for ZSH
brew 'gdbm'
brew 'git'
brew 'go'
brew 'htop'
brew 'hub'
brew 'imagemagick'
# for Ruby
brew 'jemalloc'
brew 'jq'
brew 'markdown'
# brew 'mosh'
brew 'nmap'
brew 'openssl@1.1'
# brew 'ossp-uuid'
# brew 'postgresql'
# brew 'redis'
brew 'ripgrep'
# brew 'sqlite'
brew 'starship'
brew 'telnet'
# brew 'tig'
# brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'watch'
brew 'wget'
# brew 'yarn'
brew 'z'
brew 'zsh'

cask '1password'
cask 'alfred'
cask 'choosy'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'font-fira-code'
cask 'font-firacode-nerd-font'
cask 'google-chrome'
cask 'iterm2'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'kitty'
cask 'rambox'
cask 'sizeup'
# cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'
# cask 'zoomus'
