source 'https://rubygems.org'

gem 'activesupport'
gem 'awesome_print'
gem 'dotenv'
gem 'git'
#gem 'ivar_encapsulation'
gem 'methodfinder'
gem 'pry'
gem 'pry-doc'
gem 'repl'
gem 'shenanigans'
#gem 't'
gem 'tmuxinator'
gem 'try_to'
gem 'unsavory'
