# Reference
# https://github.com/gpakosz/.tmux/blob/master/.tmux.conf
# http://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/

# -- general -------------------------------------------------------------------

set -g default-terminal "screen-256color" # colors!
setw -g xterm-keys on
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on

set -g history-limit 5000                 # boost history

# edit configuration
bind e new-window -n '~/.tmux.conf.local' "sh -c '\${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\"'"

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# -- display -------------------------------------------------------------------

set -g base-index 1         # start windows numbering at 1
setw -g pane-base-index 1   # make pane numbering consistent with windows

setw -g automatic-rename off # don't rename window to reflect current program
set -g renumber-windows on  # renumber windows when a window is closed

set -g display-panes-time 800 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

set -g status-interval 60     # redraw status line every 60 seconds

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.1' \; clear-history

# activity
set -g monitor-activity on
set -g visual-activity on

# -- navigation ----------------------------------------------------------------

# Switch back to last window easily
bind Tab last-window

# More intuitive split commands
bind | split-window -h
bind - split-window -v

set -g mouse on

# -- copy mode -----------------------------------------------------------------

# Vi key bindings in copy mode
set-option -gw mode-keys vi
unbind ]
unbind p
bind p paste-buffer
# bind -t vi-copy 'v' begin-selection
# bind -t vi-copy 'y' copy-selection

# Temporarily turn pane into window
# unbind Up
# bind Up new-window -d -n tmp \; swap-pane -s tmp.1 \; select-window -t tmp
# unbind Down
# bind Down last-window \; swap-pane -s tmp.1 \; kill-window -t tmp

# Quick logging
bind P pipe-pane -o "cat >>~/#W.log" \; display "Toggled logging to ~/#W.log"

# -- status bar ----------------------------------------------------------------

set -g status-bg black
set -g status-fg white
set -g status-left "#[fg=green][#S]"
set -g status-right "#[fg=green]#h #[fg=cyan]%R"
setw -g window-status-current-bg red
