setw -g mode-mouse on

# Use saner prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Don't rename windows
set-window-option -g allow-rename off
set-window-option -g automatic-rename off

# Vi key bindings in copy mode
set-option -gw mode-keys vi
unbind ]
unbind p
bind p paste-buffer
bind -t vi-copy 'v' begin-selection
bind -t vi-copy 'y' copy-selection

# Switch back to last window easily
bind Tab last-window

# More intuitive split commands
bind | split-window -h
bind - split-window -v

# Source config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# # Proper colors for apps inside tmux
set -g default-terminal "screen-256color"

# # Allow for faster key repetition
set -sg escape-time 0

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Temporarily turn pane into window
unbind Up
bind Up new-window -d -n tmp \; swap-pane -s tmp.1 \; select-window -t tmp
unbind Down
bind Down last-window \; swap-pane -s tmp.1 \; kill-window -t tmp

# Quick logging
bind P pipe-pane -o "cat >>~/#W.log" \; display "Toggled logging to ~/#W.log"

# Status bar
set -g status-bg black
set -g status-fg white
set -g status-left "#[fg=green][#S]"
set -g status-right "#[fg=green]#h #[fg=cyan]%R"
setw -g window-status-current-bg red
set -g status-interval 60
setw -g monitor-activity on
set -g visual-activity on
