# frozen_string_literal: true

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'

brew 'bat' # better cat
brew 'exa' # better ls
brew 'fd'  # better find
brew 'gh'
brew 'git'
brew 'htop'
brew 'imagemagick'
brew 'jemalloc' # for Ruby
brew 'jq'
brew 'markdown'
brew 'nmap'
brew 'postgresql'
brew 'redis'
brew 'ripgrep' # better grep
brew 'sqlite'
brew 'starship' # prompt for many shells
brew 'telnet'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'z'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'dropbox'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'google-chrome'
cask 'iterm2'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'zoom'
