[settings]
idiomatic_version_file_enable_tools = ["ruby", "nodejs"]
experimental = true

[settings.python]
compile = false

[settings.ruby]
compile = false

[tools]
crystal = "latest"
go = "latest"
node = "latest"
odin = "latest"
python = "latest"
ruby = "latest"
zig = "latest"
