#!/bin/sh

changed=`git diff --cached --name-only`
gemfile=`echo $changed|grep "^Gemfile$"|wc -l`
lock=`echo $changed|grep "Gemfile.lock"|wc -l`

if [ $gemfile -gt $lock ]
then
  echo "------------------- Commit ERROR ------------------------"
  echo "Both your Gemfile and your Gemfile.lock must be committed"
  echo "together. If you made changes to your Gemfile, "
  echo "make sure they also exist in your Gemfile.lock"
  echo "------------------ END Commit ERROR ----------------------"
  exit 1
fi
